# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95219a11d9f299796c986431d39d821752560b0237adfa7291e3a042a4fbc7b38054132e9c2ddfd695c03c784cbd815dc78ba5c5f53c10090649fedc8698cab2

test:
  secret_key_base: 8ff300c100d9c9626eec1eae1c8551fa4903009ba4e993f4769a7c965e31bb64a6b871557e0c3e62dde0b193c5ad03e8c6bd0af2f8e3c8eb5fd7d0f0ed3751df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
